version: "3.7"
services:
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
  etl:
    image: "cs498_etl:latest"
    working_dir: /app
    environment:
      AWS_REGION_NAME: "us-east-1"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
    depends_on:
      - dynamo
    links:
      - "dynamo:dynamo"
    volumes:
      - ./:/app
  api:
    image: "cs498_api:latest"
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      DYNAMO_ENDPOINT: "http://dynamo:8000"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      AWS_REGION_NAME: "us-east-1"
    depends_on:
      - dynamo
    links:
      - "dynamo:dynamo"
    volumes:
      - ./api:/app